spring.application.name=gerador-senhas-api

spring.datasource.url=jdbc:postgresql://localhost:5432/geradorsenhas_db
spring.profiles.include=secrets

spring.jpa.hibernate.ddl-auto=update

# Configuração do servidor https/ssl
server.port=8443
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-alias=gerador-senhas

# Habilita o log detalhado para o mapeamento de requisições
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE